### ISSUE TITLE
VORP lastname Script Error

### ISSUE THREAD

**Issue by NeoGaming22** [CryptoGenics/redm_scoreboard#2]
SCRIPT ERROR: @redm_scoreboard/scoreboardsv.lua:36: attempt to concatenate a nil value (field 'lastname')
ref (@redm_scoreboard/scoreboardsv.lua:36)
void vorpcore_sv.Utils.ApiController.getCharacter(int handle, object cb) (@vorp_core/vorpcore_sv.net.dll:0)
object <Module>.runtime_invoke_voidthis_int_object(object this, IntPtr params, IntPtr exc, IntPtr method) (@vorp_core/vorpcore_sv.net.dll:0)
handler (@redm_scoreboard/scoreboardsv.lua:33)

**Comment by CryptoGenics** [comment]
I have not used VORP before, issue is probably that your trying to view a player on scoreboard that hasn't loaded in yet (selected a name yet)

I added a possible fix, if doesn't work I can load up VORP myself to test.

**Comment by CryptoGenics** [comment]
Confirmed by installing VORP myself that the update did fix this issue.
